apiVersion: v1
kind: Service
metadata:
  name: node-vue-app
spec:
  type: LoadBalancer
  selector:
    app: node-vue-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
